url: https://luke-holly.github.io
baseurl: /Sampson-the-Longhorn-Website/

# Site settings
title: Sampson the Longhorn
email: your-email@domain.com
description: "Sampson the Longhorn is a trained, performing Texas Longhorn steer who performs throughout the Desert Southwest. This gentle beast is kind and loves to be ridden and have his picture taken."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Violet Heubner
  pic: 1
  position: Booking Manager
  social:


- name: Izzy Ordonez
  pic: 2
  position: Handler
  social:


- name: Paul Hollomon
  pic: 3
  position: Owner
  social:


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: http://facebook.com/sampsonthelonghorn


# Postal address (add as many lines as necessary)
address:
  - line: 2195 N Main
  - line: Las Cruces, NM 88007

# Build settings
markdown: kramdown
permalink: pretty
