url: https://luke-holly.github.io
baseurl: /Sampson-the-Longhorn-Website

# Site settings
title: Sampson the Longhorn
email: lp1holl@aol.com
description: "Sampson the Longhorn is a trained performing animal who does commercials, business openings, and photoshoots throughout the U.S."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: http://facebook.com/sampsonthelonghorn


# Postal address (add as many lines as necessary)
address:
  - line: 2195 N Main
  - line: Las Cruces, NM 88007

# Build settings
markdown: kramdown
permalink: pretty
